### ISSUE TITLE
build  probleam on  ubuntu 17.04

### ISSUE THREAD

**Issue by windywinter0101** [rcsoccersim/rcssserver#1]
Makefile:988: recipe for target 'rule.lo' failed
make[3]: *** [rule.lo] Error 1
make[3]: Leaving directory '/home/alice/Robocup2dInstall-master/rcssserver-15.3.0/src'
Makefile:708: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/alice/Robocup2dInstall-master/rcssserver-15.3.0/src'
Makefile:423: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/alice/Robocup2dInstall-master/rcssserver-15.3.0'
Makefile:354: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by mohammadForoughi** [comment]
Yes , i test and it's have build problem on ubuntu 17.04

**Comment by gillhofer** [comment]
Same problem on Arch Linux.

**Comment by djlrevic** [comment]
Hi guys, I fixed the same problem on Ubuntu 16.10 using ./configure CXXFLAGS='-std=c++03'

**Comment by danialbehzadi** [comment]
Fixed on Ubuntu 17.10 by `CXXFLAGS='-std=c++03'`

**Comment by chauncyzhu** [comment]
I can't find file 'configure'

**Comment by danialbehzadi** [comment]
@chauncuzhu Use the upstream code from sourceforge.

**Comment by windywinter0101** [comment]
thanks for @danialbehzadi  and  using ./configure CXXFLAGS='-std=c++11'  is building  faster than c++03

**Comment by windywinter0101** [comment]
using ./configure CXXFLAGS='-std=c++11'  solve problem
