### ISSUE TITLE
flexlexer

### ISSUE THREAD

**Issue by amzromed** [rcsoccersim/rcssserver#20]
hi
when I run the make I get dis error
I have installed flex and all the other required packages

libtool: compile:  g++ -std=c++14 -DHAVE_CONFIG_H -I. -I.. -I.. -I/usr/include -W -Wall -g -O2 -MT clangparser.lo -MD -MP -MF .deps/clangparser.Tpo -c clangparser.cpp  -fPIC -DPIC -o .libs/clangparser.o
In file included from clangparser.h:27:0,
                 from clangparser.cpp:32:
coach_lang_tok.h:34:10: fatal error: FlexLexer.h: No such file or directory
 #include <FlexLexer.h>
          ^~~~~~~~~~~~~
compilation terminated.
Makefile:1003: recipe for target 'clangparser.lo' failed
make[3]: *** [clangparser.lo] Error 1
make[3]: Leaving directory '/home/mohammad/Downloads/rcssserver-15.5.0/src'
Makefile:724: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/mohammad/Downloads/rcssserver-15.5.0/src'
Makefile:437: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/mohammad/Downloads/rcssserver-15.5.0'
Makefile:369: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by hidehisaakiyama** [comment]
What is your environment?
Ubuntu? If so, what version of ubuntu?

**Comment by herodrigues** [comment]
@amzromed you probably missed a dependency.

See https://github.com/rcsoccersim/rcssserver/issues/22 and [this tutorial](https://herodrigues.me/robocup2d-tutorial/md_sections_installing-the-soccer-simulator.html).
