### ISSUE TITLE
Problem on ubuntu 18.04 with make

### ISSUE THREAD

**Issue by xodosss** [rcsoccersim/rcssserver#22]
/usr/bin/ld: cannot find -lrcssclangparser
collect2: error: ld returned 1 exit status
Makefile:855: recipe for target 'rcssserver' failed
make[3]: *** [rcssserver] Error 1
make[3]: выход из каталога «/home/khodosss/Рабочий стол/rcssserver-15.4.0/src»
Makefile:721: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: выход из каталога «/home/khodosss/Рабочий стол/rcssserver-15.4.0/src»
Makefile:434: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: выход из каталога «/home/khodosss/Рабочий стол/rcssserver-15.4.0»
Makefile:366: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by herodrigues** [comment]
Have you installed all necessary dependencies on your Linux distro?

https://github.com/rcsoccersim/rcssserver#quick-start

**Comment by xodosss** [comment]
yes :(

**Comment by herodrigues** [comment]
Try

`sudo apt-get install libaudio-dev libpng-dev libxi-dev libglib2.0-dev libfontconfig-dev libxrender-dev`

**Comment by xodosss** [comment]
still same problem

**Comment by herodrigues** [comment]
Did you run `./configure` again after installing those packages I told you?

**Comment by xodosss** [comment]
yes

**Comment by herodrigues** [comment]
I suggest you to start over again and remove all folders you have extracted there.
Make sure you have the correct dependencies installed and I'm sure it will work.

Also, try not to use special symbols in the folder `Рабочий стол`.

**Comment by xodosss** [comment]
thanks, now it works

**Comment by dburik** [comment]
@xodosss You can also start the rcssserver in a Docker container. I used to use this one https://hub.docker.com/r/orangefoil/rcssserver an it worked fine.
