### ISSUE TITLE
the build script has something wrong?

### ISSUE THREAD

**Issue by FinchZ** [rcsoccersim/rcssserver#23]
libtool: link: g++ -std=c++14 -W -Wall -g -O2 -o .libs/rcssserver audio.o bodysender.o coach.o csvsaver.o dispsender.o field.o fullstatesender.o heteroplayer.o initsender.o initsendercoach.o initsenderlogger.o initsendermonitor.o initsenderonlinecoach.o initsenderplayer.o landmarkreader.o logger.o main.o monitor.o pcombuilder.o pcomparser.o player.o playerparam.o object.o referee.o remoteclient.o resultsaver.o serializer.o serializercoachstdv1.o serializercoachstdv7.o serializercoachstdv8.o serializercoachstdv13.o serializercoachstdv14.o serializercommonstdv1.o serializercommonstdv7.o serializercommonstdv8.o serializermonitor.o serializeronlinecoachstdv1.o serializeronlinecoachstdv6.o serializeronlinecoachstdv7.o serializeronlinecoachstdv8.o serializeronlinecoachstdv13.o serializeronlinecoachstdv14.o serializerplayerstdv1.o serializerplayerstdv7.o serializerplayerstdv8.o serializerplayerstdv13.o serializerplayerstdv14.o serverparam.o stadium.o stdoutsaver.o stdtimer.o synctimer.o team.o utility.o visualsendercoach.o visualsenderplayer.o weather.o xmlreader.o xpmholder.o player_command_parser.o player_command_tok.o  -L../rcssbase/conf -L../rcssbase/net -L../rcssbase/gzip -L/usr/lib64 -lrcssclangparser /home/finch/program/rcssserver/rcssbase/conf/.libs/librcssconfparser.so /home/finch/program/rcssserver/rcssbase/net/.libs/librcssnet.so /home/finch/program/rcssserver/rcssbase/gzip/.libs/librcssgz.so -lboost_filesystem -lboost_system -lz -lm -Wl,-rpath -Wl,/usr/local/lib
/usr/bin/ld: cannot find -lrcssclangparser
collect2: error: ld returned 1 exit status

**Comment by herodrigues** [comment]
Nothing wrong.

See https://github.com/rcsoccersim/rcssserver/issues/22 and [this tutorial](https://herodrigues.me/robocup2d-tutorial/md_sections_installing-the-soccer-simulator.html).

**Comment by FinchZ** [comment]
谢谢，我已经解决了问题。
