### ISSUE TITLE
How to update?

### ISSUE THREAD

**Issue by Sinmiuybbggh** [rcsoccersim/rcssserver#26]
Recently I have installed the rcssserver15.5.0, but I get to know that there is a new version of 15.6.0. So I downloaded the latest version. But is there anyone can tell me how to update it? I follow the same steps as my first time to install, but when I run it, it come out that: 
Version mismatched in the configuration file. You need to regenerate '/home/li/.rcssserver/server.conf' or set '15.6.0' to the 'version' option.

Can anyone give me a hand?Thank you very much.

**Comment by hidehisaakiyama** [comment]
The version number of configuration files has not been matched. Please remove the old configuration files (~/.rcssserver/*.conf), then try to start rcssserver again.

**Comment by Sinmiuybbggh** [comment]
> The version number of configuration files has not been matched. Please remove the old configuration files (~/.rcssserver/*.conf), then try to start rcssserver again.

Thanks for help.
But I have deleted all the previous packages and files, but it still doesn't work. When I type "sudo make install", it comes out as follows.
Libraries have been installed in:
   /usr/local/lib

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the '-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the 'LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the 'LD_RUN_PATH' environment variable
     during linking
   - use the '-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to '/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.

**Comment by hidehisaakiyama** [comment]
This is not a issue of rcssserver, but "export LD_LIBRARY_PATH=/usr/local/lib", "export LD_RUN_PATH=/usr/local/lib" then "sudo make installl" may resolve the problem.
