### ISSUE TITLE
Miss some shared libraries

### ISSUE THREAD

**Issue by Sinmiuybbggh** [rcsoccersim/rcssserver#27]
Now I can successfully run the server and the monitor. And it is also available to run other team's code. But when I try to build my own team, I typed "rcssclient" in the terminal and it came out like this:
rcssclient: error while loading shared libraries: librcssnet.so.1: cannot open shared object file: No such file or directory
I am also confronted with the similar problems when type "ressserver".
Thanks a lot for help.

**Comment by rug** [comment]
It seems like it can't find the shared libraries. Sometimes this may be fixed opening a shell, and executing: ‘sudo /sbin/ldconfig -v’ .

**Comment by Sinmiuybbggh** [comment]
> It seems like it can't find the shared libraries. Sometimes this may be fixed opening a shell, and executing: ‘sudo /sbin/ldconfig -v’ .
Thank you very much. It works now.
