### ISSUE TITLE
can't open the game log file ./incomplete.rcg

### ISSUE THREAD

**Issue by unknown-guy-1610** [rcsoccersim/rcssserver#28]
Hi I'm trying to install server. 
I'm getting this error. You can check my log : 

sandeep@Ubuntu:/usr/local/bin$ ./rcssserver
rcssserver-15.6.0

Copyright (C) 1995, 1996, 1997, 1998, 1999 Electrotechnical Laboratory.
2000 - RoboCup Soccer Simulator Maintenance Group.

Trying to create configuration file: /home/sandeep/.rcssserver/server.conf
Created configuration file: /home/sandeep/.rcssserver/server.conf
Trying to create configuration file: /home/sandeep/.rcssserver/player.conf
Created configuration file: /home/sandeep/.rcssserver/player.conf
Trying to create configuration file: /home/sandeep/.rcssserver/CSVSaver.conf
Created configuration file: /home/sandeep/.rcssserver/CSVSaver.conf
Simulator Random Seed: 1578554311
CSVSaver: Ready
STDOutSaver: Ready
Using simulator's random seed as Hetero Player Seed: 1578554311
wind factor: rand: 0.000000, vector: (0.000000, 0.000000)
logger.cpp: 303: can't open the game log file ./incomplete.rcg

Thanks in Advance!

**Comment by hidehisaakiyama** [comment]
You run the server under '/usr/local/bin'. Usually, that is a system directory, where only administrator accounts have write privilege.
Change the current directory to somewhere under your home directory, then start the server again.

**Comment by unknown-guy-1610** [comment]
Thanks. I added sudo before it started working.

**Comment by herodrigues** [comment]
@unknown-guy-1610 you don't have to use `sudo`. Just try to run the server on your home folder or any other folder that belongs to your user.
