### ISSUE TITLE
Say / freeform messages from online coach not working

### ISSUE THREAD

**Issue by philipholler** [rcsoccersim/rcssserver#39]
Hi robocup team!

I am using the robocup 2d soccer simulator for a project at university.

I have some trouble parsing (say "msg") messages to the server from the online coach. I simply get the (error could_not_parse_say) error.

I am using protocol version 16 on both the clients and the online coach. The server is also the newest version available on github.

I have also tried the (freeform "msg) protocol from the previous versions, but this simply returns the unknown command error.

Is this a known issue?

**Comment by hidehisaakiyama** [comment]
The protocol version 7 or later require the following format to send a freeform message:

`
    (say (freeform "msg"))
`

**Comment by philipholler** [comment]
Thank you so much for the quick answer.

This worked right away.

The entire coach section of the newest manual is missing, so i did not know what else to do, but contact you directly
