### ISSUE TITLE
Body_sense speed metric

### ISSUE THREAD

**Issue by philipholler** [rcsoccersim/rcssserver#40]
Hi rcsoccersim,

I am a bit confused regarding the metric of the max speed.

When a player is dashing with 100 power, the body_sense message receives something like 0.4 as amountOfSpeed.

In the server config, however, it says that the player_speed_max is 1.05.

Is the body_sense using another metric, and if so, which one? I assume the player_speed_max refers to 1.05 meters / second, i.e. 38 km/h.

Also the body_sense returns DirectionOfSpeed. Is this a global direction on the field, or is it relative to the body direction of the player? For example if you run backwards, it would be -180?

I hope you can help. I have looked through the manual, but i only found this:

AmountOfSpeed is an approximation of the amount of the player’s speed. 
DirectionOfSpeed is an approximation of the direction of the player’s speed.

- Philip

**Comment by hidehisaakiyama** [comment]
The player's speed reported by sense_body message is the decayed value. For example, the default type player's actual maximum speed is 1.00 and the value of player_decay is 0.4. So, if a default type player have been trying to dash by the maximum power, he would reach the theoretical maximum speed 1.0 then the speed would be decayed to 0.4 at the same cycle.

The direction of speed reported by sense_body message is relative to player's body direction.
