### ISSUE TITLE
Installation on ubuntu 20.04

### ISSUE THREAD

**Issue by constr17** [rcsoccersim/rcssserver#43]
It is a tricky to install software.

To install it on ubuntu 18.04 it was possible to use next sequence.
sudo apt-get install -y build-essential automake libboost-all-dev flex bison libqt4-dev libaudio-dev libxt-dev libxi-dev libxrender-dev libfreetype6-dev libfontconfig1-dev
./bootstrap
./configure CXXFLAGS='-std=c++14'
sudo make
sudo make install
Than configure:
sudo nano /etc/ld.so.conf
And add row /usr/local/share
Than sudo ldconfig

But for ubuntu 20.04 (or may be it last update of your server) this sequence does not work any more.
You wrote must be installed  g++, make, boost, bison, flex. They all installed and it not help.

Can you write installation sequence for ubuntu 20.04?

**Comment by herodrigues** [comment]
You're running not needed commands. The only required commands are `configure`, `make` and `make install`.
We have a releases tab, so you don't need to build it from source. But if want to do so, do not run `make` as root.

Steps:
1. Download the server source at https://github.com/rcsoccersim/rcssserver/releases/tag/rcssserver-16.0.0
2. Extract the server files and `cd`to the folder where you extracted them.
3. Make sure you have all correct dependencies installed
4. `./configure`
5. `make`
6. `sudo make install`

**Comment by constr17** [comment]
While use detailed instructions for monitor received:
`
configure: check Qt5Core >= 5.0.0
checking for QT... no
configure: error: The Qt5Core library >= 5.0.0 could not be found.
`

**Comment by herodrigues** [comment]
As the message says, you have to install Qt5

**Comment by hidehisaakiyama** [comment]
Although I'm not sure what document you are refering, I recommend you chech the latest README 
 https://github.com/rcsoccersim/rcssmonitor

**Comment by constr17** [comment]
Yes, you are right, there are different packages
