### ISSUE TITLE
Agent2d on ubuntu 20.04

### ISSUE THREAD

**Issue by constr17** [rcsoccersim/rcssserver#44]
At detail documentation [robocup2d-tutorial](https://herodrigues.me/robocup2d-tutorial/md_sections_installing-the-soccer-simulator.html) offered to install agent2d.
I tried to do it on ubuntu 20.04 (server and monitor 16.0.0 installed correctly) I receive next error while make:

make  all-recursive
make[1]: Entering directory '/home/serge/soccer/agent2d-3.1.1'
Making all in src
make[2]: Entering directory '/home/serge/soccer/agent2d-3.1.1/src'
g++ -DHAVE_CONFIG_H -I. -I..  -I../src  -I../src/chain_action -I/usr/include -W -Wall -g -O2 -MT sample_player-tackle_generator.o -MD -MP -MF .deps/sample_player-tackle_generator.Tpo -c -o sample_player-tackle_generator.o `test -f 'chain_action/tackle_generator.cpp' || echo './'`chain_action/tackle_generator.cpp
chain_action/tackle_generator.cpp:71:25: error: ‘constexpr’ needed for in-class initialization of static data member ‘const double {anonymous}::DeflectingEvaluator::not_shoot_ball_eval’ of non-integral type [-fpermissive]
   71 |     static const double not_shoot_ball_eval = 10000;
      |                         ^~~~~~~~~~~~~~~~~~~
make[2]: *** [Makefile:1115: sample_player-tackle_generator.o] Error 1
make[2]: Leaving directory '/home/serge/soccer/agent2d-3.1.1/src'
make[1]: *** [Makefile:271: all-recursive] Error 1
make[1]: Leaving directory '/home/serge/soccer/agent2d-3.1.1'
make: *** [Makefile:209: all] Error 2

Do you know how to make agent2d (https://osdn.net/projects/rctools/downloads/55186/agent2d-3.1.1.tar.gz/)?

**Comment by herodrigues** [comment]
Agent2D is not entirely related to this project and it's quite an old project (last version was released in 2012).
The tutorial you're talking about is **NOT OFFICIAL** and it was written by me to help other developers. 

Even though Agent2D was written by @hidehisaakiyama, who is one of the developers responsible for the server, it doesn't belong to this organization.
You can use any agent you want, such as [WritghtEagle2D](https://github.com/wrighteagle2d/wrighteaglebase).

I'm gonna answer your question, but please only open issues related to this project.
If you have any questions about my tutorial, open an issue at https://github.com/herodrigues/robocup2d-tutorial

**Comment by herodrigues** [comment]
Agent2D is not directly related to this project and it's quite an old project (last version was released in 2012).
The tutorial you're talking about is **NOT OFFICIAL** and it was written by me to help other developers. 

Even though Agent2D was written by @hidehisaakiyama, who is one of the developers responsible for the server, it doesn't belong to this organization.
You can use any agent you want, such as [WritghtEagle2D](https://github.com/wrighteagle2d/wrighteaglebase).

If you have any questions about my tutorial, open an issue at https://github.com/herodrigues/robocup2d-tutorial
I can answer you in there.
