### ISSUE TITLE
Player moves randomly after each move command 

### ISSUE THREAD

**Issue by gikari** [rcsoccersim/rcssserver#45]
## Steps to reproduce

1. Launch `rcssserver` and `rcssmonitor`
1. Launch `rcssclient` and type in `(init Red (version 16))`
1. Type in `(move 0 0)` a few times in a row

## Actual behavior

Player changes its position to random coordinates at each received `move` message.

## Expected behavior

Player changes its position to the specified coordinates in the message at first `move` command and do not change its position after subsequent `move` commands.

## Additional info

When sending `(move 0 0)` player turns red for a moment after changing its position (However it does not, when values are not 0 and 0). I guess this is an indication of a collision with the ball at the center of the field. Do not know for sure, but may be it's a monitor bug?

## Demo

Demo here: https://imgur.com/DZwVnbk

**Comment by hidehisaakiyama** [comment]
The red color means the player's collision with other objects.  If players and ball collide with others, the simulator tries to avoid all collisions.  In play_on mode, all objects are displaced. During the set-play period, the ball position is fixed and only players are displaced. Moreover, in before_kick_off mode, players cannot intrude in the opponent side field. If the simulator detects an intrusion, players are placed in a random position in their side field.

**Comment by gikari** [comment]
Thank you for clarification! :) May be the server could issue a warning, if player tries to occupy forbidden part of the field?

**Comment by hidehisaakiyama** [comment]
It's a reasonable improvement.
Could you post the idea as another issue?
I will try to implement it.

**Comment by gikari** [comment]
> It's a reasonable improvement.
> Could you post the idea as another issue?
> I will try to implement it.

Sure! #46
