### ISSUE TITLE
Issue a warning if the player positions itself on a forbidden area with move command

### ISSUE THREAD

**Issue by gikari** [rcsoccersim/rcssserver#46]
Currently in before_kick_off game state if the player tries to move itself to an opponent's side of a field with a move command, the server just teleports the player to a random position on its side of a field. This behavior is confusing, because the server do not warn the client about the violation of the rules and makes you think, that this is some sort of a bug. It would be nice, if the server issued a warning, for example `(warning move_to_a_forbidden_position)` or something like that.

**Comment by hidehisaakiyama** [comment]
Your suggestion has been merged in the develop branch.
Thank you!
