### ISSUE TITLE
Cannot run ./configure or make

### ISSUE THREAD

**Issue by DriesSmit** [rcsoccersim/rcssserver#48]
In the README.mb it specifies to run:

```
./configure
make
```

When I run `./configure` I get:
`bash: ./configure: No such file or directory
`

I see however than there is a configure.ac file and not a configure file. Same with the Makefile.am. How would proceed to try and resolve this issue? Thank you.

**Comment by hidehisaakiyama** [comment]
If you'd like to use the latest source tree. Please run
`autoreconf -i -f`
This command generates a configure script.

If you just need officially released versions, please check the release page.
For example, the latest official release (version 16.0.0) can be found at https://github.com/rcsoccersim/rcssserver/releases/tag/rcssserver-16.0.0
https://github.com/rcsoccersim/rcssserver/releases/download/rcssserver-16.0.0/rcssserver-16.0.0.tar.gz is a released tar ball that contains a configure script.
