### ISSUE TITLE
Error installing server inside Docker container

### ISSUE THREAD

**Issue by DriesSmit** [rcsoccersim/rcssserver#49]
Good day,

I want to create a publically available python wrapper that allows agents written in python to communicate with the RoboCup server. To start I am trying to install the rcsserver inside a docker container. Please find my attach Dockerfile:
[Dockerfile.txt](https://github.com/rcsoccersim/rcssserver/files/5911400/Dockerfile.txt)

The ./configure command runs perfectly, but when the Dockerfile executes the 'make' command I get the error message:

```
/usr/bin/ld: cannot find -lrcssclangparser
collect2: error: ld returned 1 exit status
```

Do you know how I might go about resolving this?

Thank you in advance,
Dries

**Comment by herodrigues** [comment]
Do you use non-English characters on your OS? I mean, in folders?

Read the discussion #22

**Comment by DriesSmit** [comment]
No I only use english characters as far as I can tell. I will read the discussion, thanks.

**Comment by DriesSmit** [comment]
Thanks, the docker image that was recommended in the other discussion worked for me.
