### ISSUE TITLE
Weird clearFromBall calls from referee

### ISSUE THREAD

**Issue by bandreghetti** [rcsoccersim/rcssserver#51]
I was doing some single agent reinforcement learning research and noticed something strange ocurring. Might be my lack of knowledge about a specific rule.

The referee calls clearFromBall every 100 cycles for some reason, which teleports my agent away from the ball while it (slowly but surely) approaches it.

[Here](https://youtu.be/I-Hdx2MMqHs?t=10) is a recording of it. Also here is a [.rcl](https://gist.github.com/bandreghetti/7972a72e481617505f0d1dd8479409db) where it happens along with its [.rcg](https://gist.github.com/bandreghetti/873f1698542c97af9c88092e420c2154) but not from the same game as the recording. Not sure if those will help but there they are.

Am I doing something wrong?

**Comment by herodrigues** [comment]
What's your environment for testing? What server flags are you using?

**Comment by hidehisaakiyama** [comment]
The automatic referee tries to detect a not-moving ball to avoid a stuck situation. This feature can be disabled by changing the server parameter `server::ball_stuck_area`. Its default value is 3.0. This means the automatic referee drops the ball if he detects the ball move distance is less than or equal to 3.0m for server::drop_ball_time(=100) cycles. So, you should shrink the detection area. In your case, you can just set `server::ball_stuck_area` to 0.

**Comment by bandreghetti** [comment]
Thank you! That was it 😄
